name: GH200 GITHUB_TOKEN

on:
  workflow_dispatch:

jobs:
  token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show token information
        run: |
          echo "Repository = $GITHUB_REPOSITORY"
          echo "Actor = $GITHUB_ACTOR"
          echo "Token exists = ${{ secrets.GITHUB_TOKEN != '' }}"
