name: GH200 Permissions

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Build"

  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - run: echo "Deploy"
