name: GH200 GITHUB_TOKEN

on:
  workflow_dispatch:

jobs:
  token:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test
        run: echo "Token has contents:read"
