name: GH200 Reusable Workflow

on:
  workflow_dispatch:

jobs:
  call-build:
    uses: ./.github/workflows/reusable-build.yml

    with:
      version: "9.9.9"

    secrets:
      deploy_key: ${{ secrets.DEMO_SECRET }}
