name: GH200 Events

on:
  push:
    branches:
      - main
      - "feature/**"
    paths:
      - "src/**"

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  long-job:
    runs-on: ubuntu-latest

    steps:
      - name: Long running task
        run: |
          echo "Starting..."
          sleep 9
          echo "Finished"
