name: Reusable Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

    secrets:
      deploy_key:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Show inputs
        run: |
          echo "Version = ${{ inputs.version }}"

      - name: Use secret
        run: |
          echo "Deploy key = ${{ secrets.deploy_key }}"
